
//#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[426] =
    {   0,
        0,    0,   70,   70,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   79,   77,   75,   76,   76,   49,
       77,   49,   49,   49,   44,   45,   49,   49,   49,   46,
       47,   49,   45,   49,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   49,   48,   49,   70,   71,   70,   72,   78,
       78,   55,   55,   78,    1,   78,   63,   78,   78,   78,
       67,   75,   76,   76,   49,    0,   58,   58,   56,    0,
       59,   59,    0,    0,    0,    0,   47,   47,   69,    0,
       47,   48,   48,   49,   49,   48,   48,    3,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   70,
       71,   70,   71,   72,   73,   72,   72,   74,    0,   55,
       55,    0,    0,    0,   55,    0,    0,    0,   62,   63,
        0,    0,   66,    0,   67,   58,    0,   58,   57,    0,
        0,   60,   60,    0,    0,    0,   50,   50,    0,    0,
       68,   68,    0,   47,   48,   48,   48,   38,   48,   48,
       48,   48,    9,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   73,    0,    0,    0,    0,   52,
       52,    0,    0,    0,   66,    0,   60,    0,   51,   51,
       50,   47,   68,   48,   48,   35,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   30,   48,   48,   48,
       32,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       29,   48,   48,   48,   48,   48,   48,   48,   48,   31,
       48,   53,   53,    0,   52,    0,    0,   65,   65,   65,
        0,   51,   48,   48,   48,   48,   48,   48,   48,   48,
       28,   48,   48,   48,   48,   48,   48,   39,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   26,   41,
       36,   23,   25,   48,   48,   53,    0,    0,    0,   48,
       48,   48,    7,   48,   48,   48,   27,   48,   48,   48,
       48,   48,   48,   34,   16,   48,   48,   48,   48,   48,
       48,   48,   42,   48,   48,   48,    0,    0,    0,   48,
       48,    5,   48,   48,   11,   12,   48,   48,   33,   48,
       48,   48,   48,   48,   17,   48,   48,   20,   22,   48,
        0,    0,    0,    2,   48,   48,   48,   48,   48,   48,
       43,   48,   48,   21,   19,   48,    6,    0,    0,    0,
        4,   48,   48,   48,   48,   48,   10,   48,   48,   37,

        0,   54,   54,    0,    0,   61,    8,   40,   14,   13,
       15,   18,   48,   54,    0,   64,   48,    0,   53,   53,
        0,   24,   53,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,    1,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,    1,   35,   35,   55,   56,

       57,   58,   35,   35,   59,   35,   35,   60,   35,   61,
       62,   35,   35,   35,   63,   35,   64,   35,   35,   35,
       35,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    4,    1,    5,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1,    6,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[450] =
    {   0,
        0,    0,   67,   69,   73,   81,    0,    0,   84,   85,
      743,  742,   87,   90,  749,  752,   96,  752,  745,  725,
       99,  104,   95,  752,  752,  724,   91,   99,  726,  101,
      108,   74,  722,   88,   86,    0,   91,   91,   94,  710,
      701,   36,  697,  106,   99,  696,  114,  105,  117,  698,
      696,  705,  714,  676,  114,  144,  752,  148,  155,  158,
      172,  752,  175,  181,  752,  727,    0,  752,  674,  165,
        0,  188,  752,  729,  752,  191,  752,  193,  752,  199,
      752,  728,  183,  669,  205,  710,  182,  186,  752,  209,
      197,    0,  203,  706,  705,    0,  684,    0,  103,  681,

      191,  682,  695,  679,  683,  681,  187,  690,  681,  689,
      673,  673,  667,  688,  669,  670,  674,  138,  187,  666,
      663,  202,  203,  671,  681,  680,  675,  674,  637,  230,
      752,  232,  752,  234,  752,  252,  254,  752,  256,  752,
      258,  265,  272,  275,  752,  278,  285,  694,  752,    0,
      639,  234,  752,  246,    0,  752,  291,  293,  752,  298,
      281,  752,  288,  644,  300,  304,  752,  307,  298,  312,
      752,  315,  679,  678,  657,  655,  646,    0,  657,  659,
      662,  650,    0,  660,  663,  643,  643,  642,  643,  643,
      649,  656,  651,  636,  651,  637,  651,  650,  629,  628,

      647,  632,  645,  640,  627,  624,  625,  629,  631,  620,
      635,  620,  622,  602,  752,  317,  319,  327,  343,  752,
      333,  349,  603,  321,  650,  333,  752,  596,  752,  351,
      752,  636,  752,  618,  614,    0,  627,  613,  612,  613,
      610,  611,  606,  612,  603,  618,    0,  600,  613,  604,
        0,  612,  594,  600,  595,  602,  609,  590,  587,  588,
        0,  603,  596,  599,  591,  583,  596,  595,  578,    0,
      544,  752,  355,  358,  752,  361,  510,  752,  752,  557,
      494,  752,  508,  497,  444,  327,  456,  458,  454,  445,
        0,  455,  435,  435,  437,  451,  445,    0,  431,  444,

      439,  432,  427,  436,  443,  438,  434,  427,    0,    0,
        0,    0,    0,  439,  404,  752,  364,  397,  404,  416,
      429,  428,    0,  413,  426,  406,    0,  405,  416,  414,
      421,  413,  405,    0,    0,  404,  404,  401,  415,  398,
      416,  413,    0,  409,  398,    0,  367,  382,  380,  407,
      397,    0,  401,  395,    0,    0,  399,  402,    0,  402,
      394,  384,  386,  363,    0,  373,  364,    0,    0,  354,
      373,  337,  324,    0,  345,  347,  305,  331,  286,  265,
        0,  258,  228,    0,    0,  219,    0,  375,  380,  382,
        0,  208,  182,  196,  175,  145,    0,  127,  131,    0,

      387,  752,  389,  395,  399,  752,    0,    0,    0,    0,
        0,    0,  117,  752,  404,  752,  107,  406,  752,  412,
      418,    0,  752,  421,  752,  486,  492,  498,  504,  510,
      516,  522,  525,  526,  532,  538,  544,  550,  556,  562,
      568,  574,  580,  586,  592,  598,  604,  610,  616
    } ;

static const flex_int16_t yy_def[450] =
    {   0,
      425,    1,  426,  426,  427,  427,  428,  428,  429,  429,
      430,  430,  431,  431,  425,  425,  425,  425,  425,  425,
      432,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      433,  425,  425,  425,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  425,  434,  425,  435,  425,  435,  436,  437,
      437,  425,  437,  437,  425,  438,  439,  425,  425,  440,
      441,  425,  425,  425,  425,  432,  425,  432,  425,  442,
      425,  425,  443,  425,  444,  425,  425,  425,  425,  445,
      433,  434,  434,  425,  425,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  435,
      425,  435,  425,  436,  425,  436,  436,  425,  437,  425,
      437,  437,  437,  437,  425,  437,  446,  438,  425,  439,
      425,  440,  425,  447,  441,  425,  442,  442,  425,  442,
      443,  425,  443,  425,  444,  444,  425,  444,  425,  445,
      425,  445,  425,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  425,  446,  437,  446,  446,  425,
      446,  446,  425,  440,  425,  447,  425,  425,  425,  444,
      425,  425,  425,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  425,  446,  437,  425,  446,  425,  425,  425,  425,
      425,  425,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  425,  437,  425,  425,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  437,  425,  425,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      437,  425,  425,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  448,  425,  425,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      448,  425,  448,  448,  425,  425,  434,  434,  434,  434,
      434,  434,  434,  425,  449,  425,  434,  449,  425,  449,
      449,  434,  425,  449,    0,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425
    } ;

static const flex_int16_t yy_nxt[822] =
    {   0,
       16,   17,   18,   19,   17,   20,   21,   22,   23,   24,
       25,   25,   26,   27,   25,   28,   29,   30,   31,   24,
       32,   33,   34,   24,   35,   36,   37,   38,   39,   40,
       41,   36,   42,   43,   36,   36,   44,   45,   46,   47,
       48,   49,   50,   51,   36,   52,   36,   36,   36,   25,
       16,   25,   53,   16,   36,   36,   36,   36,   36,   36,
       36,   36,   54,   36,   36,   25,   55,   25,   24,   57,
       58,   57,   58,  107,   61,   62,   63,   61,  108,   59,
       64,   59,   61,   62,   63,   61,   67,   67,   64,   71,
       67,   67,   71,   71,   94,   75,   71,   72,   73,   74,

       72,   77,   78,   75,   75,   79,   81,   82,   83,   75,
       95,   97,   75,   89,   75,   86,   75,   87,   90,  101,
       75,   75,   75,  102,   86,   75,   91,  113,   98,   99,
      100,  103,  110,  119,  111,   75,   93,  114,  116,  176,
      104,  121,  177,  120,  422,  122,  131,  132,  123,   80,
      133,  132,  117,  112,  118,  417,  124,  135,  136,  125,
      140,  141,   84,  413,   93,  142,  199,  137,  412,   85,
      200,  153,  138,  143,  140,  141,  143,  145,  141,  144,
       75,  154,  142,  140,  141,  162,  163,  411,  142,   72,
       73,   74,   72,   77,   78,  156,   78,   79,   86,   79,

       87,   77,  158,  410,   88,  159,  166,  167,  168,  166,
      169,  171,  172,   86,  169,   91,  173,  179,  173,  187,
      180,  174,  201,  202,  409,   93,  205,  207,  188,  408,
      181,  208,  131,  132,  133,  132,  135,  136,  169,  146,
      153,   80,  169,   80,  206,  407,  425,  400,  147,  160,
      154,  425,  225,   93,  215,  136,  135,  136,  140,  141,
      145,  141,  226,  142,  425,  142,  137,  140,  141,  425,
      399,  138,  142,  143,  140,  141,  143,  140,  141,  144,
      140,  141,  142,  162,  163,  142,  219,  220,  221,  219,
      227,  163,  222,   77,  158,  156,  158,  159,  398,  159,

       77,  158,  229,  230,  159,  166,  167,  168,  166,  231,
      230,  173,  397,  173,  171,  172,  232,  233,  172,  272,
      273,  140,  141,  396,  222,  390,  142,  278,  390,  272,
      273,  393,  216,  146,  222,  275,  273,  154,  217,  280,
      222,  160,  147,  160,  219,  220,  221,  219,  160,  226,
      222,  272,  273,  282,  230,  323,  222,  316,  273,  324,
      140,  141,  222,  272,  273,  142,  140,  141,  222,  140,
      141,  142,  394,  274,  142,  140,  141,  402,  403,  395,
      142,  405,  404,  390,  405,  392,  390,  391,  406,  402,
      403,  414,  403,  389,  404,  387,  404,  402,  403,  386,

      405,  385,  404,  405,  384,  416,  419,  420,  419,  420,
      383,  421,  382,  421,  423,  420,  276,  317,  381,  421,
      419,  420,  371,  419,  420,  421,  380,  347,  421,  388,
      379,  378,  377,  376,  375,  374,  373,  372,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  346,  415,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  322,  424,   56,   56,   56,   56,
       56,   56,   60,   60,   60,   60,   60,   60,   65,   65,

       65,   65,   65,   65,   66,   66,   66,   66,   66,   66,
       68,   68,   68,   68,   68,   68,   70,   70,   70,   70,
       70,   70,   76,   76,   76,   76,   76,   76,   92,   92,
       96,   96,  130,  130,  321,  130,  130,  130,  134,  134,
      134,  134,  134,  134,  139,  139,  139,  139,  139,  139,
      148,  320,  148,  148,  148,  148,  150,  319,  150,  150,
      150,  150,  152,  279,  152,  152,  152,  152,  155,  318,
      155,  155,  155,  155,  157,  157,  157,  157,  157,  157,
      161,  161,  161,  161,  161,  161,  165,  165,  165,  165,
      165,  165,  170,  170,  170,  170,  170,  170,  218,  218,

      218,  218,  218,  218,  224,  315,  224,  224,  224,  224,
      401,  401,  401,  401,  401,  401,  418,  418,  418,  418,
      418,  418,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  232,  281,  279,  277,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  174,  232,  228,  223,

      149,  214,  213,  212,  211,  210,  209,  204,  203,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  186,
      185,  184,  183,  182,  178,  175,   75,   75,   88,  164,
       81,   73,  151,  149,  129,   75,  128,  127,  126,  115,
      109,  106,  105,   75,   88,   75,   75,   73,  425,   69,
       69,   15,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425
    } ;

static const flex_int16_t yy_chk[822] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,   42,    5,    5,    5,    5,   42,    3,
        5,    4,    6,    6,    6,    6,    9,   10,    6,   13,
        9,   10,   14,   13,   32,   32,   14,   17,   17,   17,

       17,   21,   21,   23,   27,   21,   22,   22,   22,   34,
       34,   35,   27,   30,   28,   28,   23,   28,   30,   38,
       28,   28,   30,   38,   31,   22,   31,   45,   35,   37,
       37,   39,   44,   48,   44,   55,   31,   45,   47,   99,
       39,   49,   99,   48,  417,   49,   56,   56,   49,   21,
       58,   58,   47,   44,   47,  413,   49,   59,   59,   49,
       60,   60,   22,  399,   31,   60,  118,   59,  398,   22,
      118,   70,   59,   61,   61,   61,   61,   63,   63,   61,
       55,   70,   63,   64,   64,   83,   83,  396,   64,   72,
       72,   72,   72,   76,   76,   78,   78,   76,   87,   78,

       87,   80,   80,  395,   88,   80,   85,   85,   85,   85,
       87,   90,   90,   91,   88,   91,   93,  101,   93,  107,
      101,   93,  119,  119,  394,   91,  122,  123,  107,  393,
      101,  123,  130,  130,  132,  132,  134,  134,   87,   64,
      152,   76,   88,   78,  122,  392,  134,  386,   64,   80,
      152,  134,  154,   91,  136,  136,  137,  137,  139,  139,
      141,  141,  154,  139,  136,  141,  137,  142,  142,  136,
      383,  137,  142,  143,  143,  143,  143,  144,  144,  143,
      146,  146,  144,  161,  161,  146,  147,  147,  147,  147,
      163,  163,  147,  157,  157,  158,  158,  157,  382,  158,

      160,  160,  165,  165,  160,  166,  166,  166,  166,  168,
      168,  169,  380,  169,  170,  170,  169,  172,  172,  216,
      216,  217,  217,  379,  216,  373,  217,  224,  373,  218,
      218,  377,  142,  144,  218,  221,  221,  224,  146,  226,
      221,  157,  144,  158,  219,  219,  219,  219,  160,  226,
      219,  222,  222,  230,  230,  286,  222,  273,  273,  286,
      274,  274,  273,  276,  276,  274,  317,  317,  276,  347,
      347,  317,  378,  217,  347,  371,  371,  388,  388,  378,
      371,  389,  388,  390,  389,  376,  390,  375,  390,  401,
      401,  403,  403,  372,  401,  370,  403,  404,  404,  367,

      405,  366,  404,  405,  364,  405,  415,  415,  418,  418,
      363,  415,  362,  418,  420,  420,  222,  274,  361,  420,
      421,  421,  347,  424,  424,  421,  360,  317,  424,  371,
      358,  357,  354,  353,  351,  350,  349,  348,  345,  344,
      342,  341,  340,  339,  338,  337,  336,  333,  332,  331,
      330,  329,  328,  326,  325,  324,  322,  321,  320,  319,
      318,  315,  404,  314,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  297,  296,  295,  294,  293,  292,
      290,  289,  288,  287,  285,  421,  426,  426,  426,  426,
      426,  426,  427,  427,  427,  427,  427,  427,  428,  428,

      428,  428,  428,  428,  429,  429,  429,  429,  429,  429,
      430,  430,  430,  430,  430,  430,  431,  431,  431,  431,
      431,  431,  432,  432,  432,  432,  432,  432,  433,  433,
      434,  434,  435,  435,  284,  435,  435,  435,  436,  436,
      436,  436,  436,  436,  437,  437,  437,  437,  437,  437,
      438,  283,  438,  438,  438,  438,  439,  281,  439,  439,
      439,  439,  440,  280,  440,  440,  440,  440,  441,  277,
      441,  441,  441,  441,  442,  442,  442,  442,  442,  442,
      443,  443,  443,  443,  443,  443,  444,  444,  444,  444,
      444,  444,  445,  445,  445,  445,  445,  445,  446,  446,

      446,  446,  446,  446,  447,  271,  447,  447,  447,  447,
      448,  448,  448,  448,  448,  448,  449,  449,  449,  449,
      449,  449,  269,  268,  267,  266,  265,  264,  263,  262,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  250,
      249,  248,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  235,  234,  232,  228,  225,  223,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  182,
      181,  180,  179,  177,  176,  175,  174,  173,  164,  151,

      148,  129,  128,  127,  126,  125,  124,  121,  120,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  106,
      105,  104,  103,  102,  100,   97,   95,   94,   86,   84,
       82,   74,   69,   66,   54,   53,   52,   51,   50,   46,
       43,   41,   40,   33,   29,   26,   20,   19,   15,   12,
       11,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
//#line 1 "instrument.l"
/* In Emacs, please make this -*-c-*- mode. Thanks. */
/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright (C) 1997-2007, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Kernel: instrument.l
*
* %Identification
* Written by: K.N.
* Date: Jul  1, 1997
* Origin: Risoe
* Release: McStas 1.6
* Version: $Revision$
*
* Flex scanner for instrument definition files.
*
*******************************************************************************/
/* Definition section. */
/* Do not use the `yywrap feature' - only scan a single file (see Flex manual). */
//#line 31 "instrument.l"
#include <string.h>
#include <math.h>
#include <stdio.h>

// On Windows and using cl.exe, avoid
// unistd.h and map popen/pclose to fallback _ versions
#ifdef _MSC_EXTENSIONS
#define YY_NO_UNISTD_H
#define popen _popen
#define pclose _pclose
#endif

#include "mccode.h"
#include "instrument.tab.h"

/* Fix things for bison option %pure_parser. */
#define YY_DECL int yylex(YYSTYPE *yylvalp)
#define yylval (*yylvalp)


/* Structure to hold the state of a file being parsed. */
struct file_state
  {
    YY_BUFFER_STATE buffer;
    char *filename;
    char *switch_line;
    int line;
    int oldstate;   /* Saved lexer start condition. */
    int visible_eof;    /* If true, tell parser about end-of-file. */
  };

#define MAX_INCLUDE 256
static struct file_state file_stack[MAX_INCLUDE + 1];
static int file_stack_ptr = 0;
static char *switch_line = NULL;

static void push_include(char *name);

//#line 833 "lex.yy.c"
/* Lexer states. */
/* The state ccomment is used for scanning c-style comments. The state ccode
   is used when scanning embedded C code blocks. */

/* The state initial_token is only used to output an initial token to
   discriminate between parsing general instrument definitions and autoloaded
   component definitions. */

/* Get file name in %include. */

/* Get full %include line within C code blocks. */

/* Get file name in %include within C code blocks. */

/* Abbreviations. */
//#line 849 "lex.yy.c"


// NOTE: can we alter this in instrument.l ???
/*
#define INITIAL 0
#define ccomment 1
#define ccode 2
#define initial_token 3
#define inclname 4
#define cfullincl 5
#define cinclname 6
*/

static const int INITIAL = 0;
static const int ccomment = 1;
static const int ccode = 2;
static const int initial_token = 3;
static const int inclname = 4;
static const int cfullincl = 5;
static const int cinclname = 6;


#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
//#line 104 "instrument.l"


//#line 107 "instrument.l"
 /* Initially, output a single token to the parser to tell it whether to parse
    general instrument definitions or autoloaded component definitions. */
//#line 1078 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 752 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
//#line 110 "instrument.l"
YY_RULE_SETUP
case YY_STATE_EOF(initial_token):
//#line 110 "instrument.l"
{
      yyless(0);
      BEGIN(INITIAL);
      return parse_restricted ? TOK_RESTRICTED : TOK_GENERAL;
    }
	YY_BREAK
case 2:
YY_RULE_SETUP
//#line 116 "instrument.l"
return TOK_ABSOLUTE;
	YY_BREAK
case 3:
YY_RULE_SETUP
//#line 117 "instrument.l"
return TOK_AT;
	YY_BREAK
case 4:
YY_RULE_SETUP
//#line 118 "instrument.l"
return TOK_COMPONENT;
	YY_BREAK
case 5:
YY_RULE_SETUP
//#line 119 "instrument.l"
return TOK_DECLARE;
	YY_BREAK
case 6:
YY_RULE_SETUP
//#line 120 "instrument.l"
return TOK_USERVARS;
	YY_BREAK
case 7:
YY_RULE_SETUP
//#line 121 "instrument.l"
return TOK_DEFINE;
	YY_BREAK
case 8:
YY_RULE_SETUP
//#line 122 "instrument.l"
return TOK_DEFINITION;
	YY_BREAK
case 9:
YY_RULE_SETUP
//#line 123 "instrument.l"
return TOK_END;
	YY_BREAK
case 10:
YY_RULE_SETUP
//#line 124 "instrument.l"
return TOK_DISPLAY;
	YY_BREAK
case 11:
YY_RULE_SETUP
//#line 125 "instrument.l"
return TOK_DISPLAY; /* DISPLAY is alias to MCDISPLAY */
	YY_BREAK
case 12:
YY_RULE_SETUP
//#line 126 "instrument.l"
return TOK_FINALLY;
	YY_BREAK
case 13:
YY_RULE_SETUP
//#line 127 "instrument.l"
return TOK_INITIALISE;
	YY_BREAK
case 14:
YY_RULE_SETUP
//#line 128 "instrument.l"
return TOK_INITIALISE;  /* INITIALISE is alias to INITIALIZE */
	YY_BREAK
case 15:
YY_RULE_SETUP
//#line 129 "instrument.l"
return TOK_INSTRUMENT;
	YY_BREAK
case 16:
YY_RULE_SETUP
//#line 130 "instrument.l"
return TOK_PRIVATE;
	YY_BREAK
case 17:
YY_RULE_SETUP
//#line 131 "instrument.l"
return TOK_PRIVATE; /* PRIVATE is alias to OUTPUT */
	YY_BREAK
case 18:
YY_RULE_SETUP
//#line 132 "instrument.l"
return TOK_PARAMETERS;
	YY_BREAK
case 19:
YY_RULE_SETUP
//#line 133 "instrument.l"
return TOK_RELATIVE;
	YY_BREAK
case 20:
YY_RULE_SETUP
//#line 134 "instrument.l"
return TOK_ROTATED;
	YY_BREAK
case 21:
YY_RULE_SETUP
//#line 135 "instrument.l"
return TOK_PREVIOUS;
	YY_BREAK
case 22:
YY_RULE_SETUP
//#line 136 "instrument.l"
return TOK_SETTING;
	YY_BREAK
case 23:
YY_RULE_SETUP
//#line 137 "instrument.l"
return TOK_STATE; /* obsolete -> error */
	YY_BREAK
case 24:
YY_RULE_SETUP
//#line 138 "instrument.l"
return TOK_POL;   /* obsolete -> error */
	YY_BREAK
case 25:
YY_RULE_SETUP
//#line 139 "instrument.l"
return TOK_TRACE;
	YY_BREAK
case 26:
YY_RULE_SETUP
//#line 140 "instrument.l"
return TOK_SHARE;
	YY_BREAK
case 27:
YY_RULE_SETUP
//#line 141 "instrument.l"
return TOK_EXTEND;
	YY_BREAK
case 28:
YY_RULE_SETUP
//#line 142 "instrument.l"
return TOK_GROUP;         /* extended McStas grammar */
	YY_BREAK
case 29:
YY_RULE_SETUP
//#line 143 "instrument.l"
return TOK_SAVE;
	YY_BREAK
case 30:
YY_RULE_SETUP
//#line 144 "instrument.l"
return TOK_JUMP;          /* extended McStas grammar */
	YY_BREAK
case 31:
YY_RULE_SETUP
//#line 145 "instrument.l"
return TOK_WHEN;          /* extended McStas grammar */
	YY_BREAK
case 32:
YY_RULE_SETUP
//#line 146 "instrument.l"
return TOK_NEXT;          /* extended McStas grammar */
	YY_BREAK
case 33:
YY_RULE_SETUP
//#line 147 "instrument.l"
return TOK_ITERATE;       /* extended McStas grammar */
	YY_BREAK
case 34:
YY_RULE_SETUP
//#line 148 "instrument.l"
return TOK_MYSELF;        /* extended McStas grammar */
	YY_BREAK
case 35:
YY_RULE_SETUP
//#line 149 "instrument.l"
return TOK_COPY;          /* extended McStas grammar */
	YY_BREAK
case 36:
YY_RULE_SETUP
//#line 150 "instrument.l"
return TOK_SPLIT;         /* extended McStas grammar */
	YY_BREAK
case 37:
YY_RULE_SETUP
//#line 151 "instrument.l"
return TOK_REMOVABLE;     /* extended McStas grammar with include */
	YY_BREAK
case 38:
YY_RULE_SETUP
//#line 152 "instrument.l"
return TOK_CPUONLY;       /* extended McStas grammar with GPU-CPU support */
	YY_BREAK
case 39:
YY_RULE_SETUP
//#line 153 "instrument.l"
return TOK_NOACC; 
	YY_BREAK
case 40:
YY_RULE_SETUP
//#line 154 "instrument.l"
return TOK_DEPENDENCY;
	YY_BREAK
case 41:
YY_RULE_SETUP
//#line 155 "instrument.l"
return TOK_SHELL;         /* extended McStas grammar with SHELL commands pre-cogen */
	YY_BREAK
case 42:
YY_RULE_SETUP
//#line 156 "instrument.l"
return TOK_SEARCH;        /* additional Instrument/Component search directories */
	YY_BREAK
case 43:
YY_RULE_SETUP
//#line 157 "instrument.l"
return TOK_METADATA;
	YY_BREAK
case 44:
YY_RULE_SETUP
//#line 160 "instrument.l"
return yytext[0]; /* Punctuation. */
	YY_BREAK
case 45:
YY_RULE_SETUP
//#line 161 "instrument.l"
return yytext[0]; /* Operator. */
	YY_BREAK
case 46:
YY_RULE_SETUP
//#line 162 "instrument.l"
return yytext[0]; /* special name, unit separator */
	YY_BREAK
case 47:
YY_RULE_SETUP
//#line 164 "instrument.l"
yylval.number = str_dup(yytext); return TOK_NUMBER;
	YY_BREAK
/* Note: Since ID overlaps with NUMBER (eg. "2E3"), ID must come
    after NUMBER */
case 48:
YY_RULE_SETUP
//#line 167 "instrument.l"
yylval.string = str_dup(yytext); return TOK_ID;
	YY_BREAK
/* Scanning all other C tokens used in expressions for component
 * actual parameters.
 * IMPORTANT!: Whenever a token is removed from here to make an independent
 * separate token, the new token must be added to the parser rules for
 * genatexp/topatexp.
 */
case 49:
YY_RULE_SETUP
//#line 175 "instrument.l"
{
      yylval.string = str_dup(yytext);
      return TOK_CTOK;
\
    }
	YY_BREAK
/* Scanning embedded C code. */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
//#line 183 "instrument.l"
{
      yylval.linenum = instr_current_line;
      instr_current_line++;
      BEGIN(ccode);
      return TOK_CODE_START;
    }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
//#line 189 "instrument.l"
{
      instr_current_line++;
      print_error("%%{ token not on a line by itself "
                  "on line %d of file '%s': %s.\n",
              instr_current_line, instr_current_filename, yytext);
      return TOK_INVALID;
    }
	YY_BREAK

/* normal %} symbol to end C code block */
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
//#line 199 "instrument.l"
instr_current_line++; BEGIN(INITIAL); return TOK_CODE_END;
	YY_BREAK
/* %} symbol surrounded by some unrelevant stuff */
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
//#line 201 "instrument.l"
{
        instr_current_line++;
        print_warn(NULL, "%%} terminator not on a line by itself "
                    "on line %d of file '%s': %s.\n",
              instr_current_line, instr_current_filename, yytext);
      }
	YY_BREAK
/* %include full line -> jump to cfullincl state */
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
//#line 208 "instrument.l"
{
      yyless(0);  /* re-use the current line, but within cfullincl state */
      BEGIN(cfullincl);
      }
	YY_BREAK
/* full line as C code */
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
//#line 213 "instrument.l"
{
        instr_current_line++;
        yylval.string = str_dup(yytext);
        return TOK_CODE_LINE;
      }
	YY_BREAK
/* end ccode */
/* Quoted strings. Simple version: no escape sequences. */
case 56:
YY_RULE_SETUP
//#line 221 "instrument.l"
{
        yylval.string =
          str_dup_n(&yytext[1], strlen(yytext) - 2);
        return TOK_STRING;
      }
	YY_BREAK
/* Quoted strings with escape sequence (e.g Win32 path): preserve all chars */
case 57:
YY_RULE_SETUP
//#line 227 "instrument.l"
{
        yylval.string = str_dup_n(&yytext[1], strlen(yytext) - 2);
        return TOK_STRING;
      }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
//#line 231 "instrument.l"
{
        print_error("Error: Unterminated string "
                    "on line %d of file '%s': %s.\n",
              instr_current_line, instr_current_filename, yytext);
      }
	YY_BREAK
/* %-style comments - ignore everything to end of line. */
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
//#line 238 "instrument.l"
instr_current_line++; /* Ignore comment. */
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
//#line 239 "instrument.l"
instr_current_line++; /* Ignore comment. */
	YY_BREAK
/* Include files for McStas comp/instr (INITIAL state). */
/* then next token is the file name */
case 61:
YY_RULE_SETUP
//#line 243 "instrument.l"
BEGIN(inclname);
	YY_BREAK

/* name ends with a quote char -> include as INITIAL state */
case 62:
YY_RULE_SETUP
//#line 246 "instrument.l"
{
        yytext[yyleng - 1] = '\0';
        BEGIN(INITIAL);
        if (verbose) fprintf(stderr, "Embedding %s\n", yytext);
        push_include(yytext);
      }
	YY_BREAK
/* name contains char, including quote and \n -> not valid */
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
//#line 253 "instrument.l"
{
        print_error("Error in %%include statement "
                    "on line %d of file '%s': %s.\n",
              instr_current_line, instr_current_filename, yytext);
        BEGIN(INITIAL);
      }
	YY_BREAK
/* end inclname */
/* Include files within C code blocks (ccode state)*/
/* next token is full line, regenerated by yyless(0) */
case 64:
YY_RULE_SETUP
//#line 262 "instrument.l"
BEGIN(cinclname);
	YY_BREAK

/* name ends with a quote char, with extension -> include as ccode state */
case 65:
YY_RULE_SETUP
//#line 265 "instrument.l"
{
        yytext[yyleng - 1] = '\0';
        BEGIN(ccode);
        if (verbose) fprintf(stderr, "Embedding file      %s\n", yytext);
        push_include(yytext);
      }
	YY_BREAK
/* name ends with a quote char, but no ext -> include as ccode state
   * this occurs when importing a library .h/.c The .c is only included
   * when instr->runtime option is true
   */
case 66:
YY_RULE_SETUP
//#line 275 "instrument.l"
{
        char *tmp0, *tmp1;
        yytext[yyleng - 1] = '\0';
        tmp0 = str_dup(yytext);
        if (!symtab_lookup(lib_instances, tmp0))
        {
          tmp1 = str_cat(tmp0, ".h", NULL);
          if (instrument_definition->include_runtime)
          {
            switch_line = str_cat(tmp0, ".c", NULL);
          }
          else
            fprintf(stderr,"Dependency: %s.o\n", tmp0);

          BEGIN(ccode);
          if (verbose) fprintf(stderr, "Embedding library   %s\n", tmp1);

          push_include(tmp1);
          symtab_add(lib_instances, tmp0, NULL);
          str_free(tmp1);
        }
        else
        {
          BEGIN(ccode);
          instr_current_line++;  /* library was previously embedded */
        }
        str_free(tmp0);
      }
	YY_BREAK
/* name contains char, including quote and \n -> not valid */
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
//#line 304 "instrument.l"
{
        print_error("Error in %%include statement "
                    "on line %d of file '%s': %s.\n",
              instr_current_line, instr_current_filename, yytext);
        BEGIN(ccode);
      }
	YY_BREAK
/* end  cinclname */
/* C++ "//"-style comments - ignore everything to end of line. */
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
//#line 313 "instrument.l"
instr_current_line++; /* Ignore comment. */
	YY_BREAK
/* C-style comments. */
case 69:
YY_RULE_SETUP
//#line 316 "instrument.l"
BEGIN(ccomment);
	YY_BREAK

case 70:
YY_RULE_SETUP
//#line 318 "instrument.l"
/* Ignore comment. */
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
//#line 319 "instrument.l"
instr_current_line++; /* Ignore comment. */
	YY_BREAK
case 72:
YY_RULE_SETUP
//#line 320 "instrument.l"
/* Ignore comment. */
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
//#line 321 "instrument.l"
instr_current_line++; /* Ignore comment. */
	YY_BREAK
case 74:
YY_RULE_SETUP
//#line 322 "instrument.l"
BEGIN(INITIAL); /* End of comment. */
	YY_BREAK

case 75:
YY_RULE_SETUP
//#line 325 "instrument.l"
/* Ignore whitespace. */
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
//#line 326 "instrument.l"
instr_current_line++; /* Ignore whitespace. */
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ccode):
//#line 328 "instrument.l"
{
      if(file_stack_ptr <= 0)
      {
        /* EOF on main instrument file. */
        yyterminate();
      }
      else
      {
        --file_stack_ptr;
        yy_delete_buffer(YY_CURRENT_BUFFER);
        yy_switch_to_buffer(file_stack[file_stack_ptr].buffer);
        instr_current_filename = file_stack[file_stack_ptr].filename;
        instr_current_line = file_stack[file_stack_ptr].line;
        switch_line        = file_stack[file_stack_ptr].switch_line;
        if (switch_line)
        {
          char *tmp0;
          tmp0 = str_dup(switch_line);
          str_free(switch_line);
          switch_line = NULL;
          BEGIN(ccode);
          if (verbose) fprintf(stderr, "Embedding library   %s\n", tmp0);
          push_include(tmp0);
          str_free(tmp0);
        }
        else
        {
          BEGIN(file_stack[file_stack_ptr].oldstate);
          if(file_stack[file_stack_ptr].visible_eof)
            yyterminate();
        }

      }
    }
	YY_BREAK
case 77:
YY_RULE_SETUP
//#line 363 "instrument.l"
{
      print_error("Invalid character `%s' "
                  "on line %d of file '%s'.\n",
            yytext, instr_current_line, instr_current_filename);
      return TOK_INVALID;
    }
	YY_BREAK
case 78:
YY_RULE_SETUP
//#line 372 "instrument.l"
ECHO;
	YY_BREAK
//#line 1713 "lex.yy.c"
case YY_STATE_EOF(ccomment):
case YY_STATE_EOF(inclname):
case YY_STATE_EOF(cfullincl):
case YY_STATE_EOF(cinclname):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 425);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

//#line 372 "instrument.l"


/* User code section. */

/* This flag is set when autoloading component definitions to make the lexer
   output the special initial token to switch the parser to restricted
   mode. */
int parse_restricted = 0;

/* Prepare to run lexical analysis on new file. */
void
lex_new_file(FILE *file)
{
  parse_restricted = 0;
  BEGIN(initial_token);
  yyrestart(file);
}


/* This handles the details of switching the lexer to a new file. */
static void
push_file(FILE *file, int restricted, int visible_eof)
{
  if(file_stack_ptr >= MAX_INCLUDE)
    fatal_error("Too deeply nested includes "
                "on line %d of file '%s'.\n",
              instr_current_line, instr_current_filename);
  file_stack[file_stack_ptr].buffer = YY_CURRENT_BUFFER;
  file_stack[file_stack_ptr].filename = instr_current_filename;
  file_stack[file_stack_ptr].line = instr_current_line;
  file_stack[file_stack_ptr].oldstate = YY_START;
  file_stack[file_stack_ptr].visible_eof = visible_eof;
  file_stack[file_stack_ptr].switch_line = switch_line;
  file_stack_ptr++;

  instr_current_line = 1;

  yy_switch_to_buffer(yy_create_buffer(file, YY_BUF_SIZE));
  parse_restricted = restricted;
}

/* Handle a new %include file. */
void
push_include(char *name)
{
  FILE *file;

  file = open_file_search(name);
  if(file == NULL)
    fatal_error("Cannot open include file '%s' "
                "on line %d of file '%s'.\n",
              name, instr_current_line, instr_current_filename);
  push_file(file, FALSE, FALSE);
  instr_current_filename = name;
  instr_current_line = 1;
}

/* Handle a new autoincluded file (uses recursive parser call). */
void
push_autoload(FILE *file)
{
  push_file(file, TRUE, TRUE);
  BEGIN(initial_token);
}

